name: grism_overlap-3.8
channels:
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - astropy>=4.3.1
  - ipython>=7.12.0
  - jupyter>=1.0.0
  - numpy>=1.18.1
  - pytest>=5.4.3
  - python>3.8, <3.9
  - scipy>=1.2.1
  - pysiaf>=0.11.0
  - matplotlib>=3.3.4
  - pip:
    - tk>=0.1.0