name: grism_overlap-3.8
channels:
  - http://ssb.stsci.edu/astroconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - python==3.8.10
  - pip:
    - astropy==5.0.4
    - astroquery==0.4.6
    - bokeh>=2.2.3
    - hotsoss
    - ipython==8.2.0
    - jupyter==1.0.0
    - numpy==1.22.3
    - PyQt5==5.15.6
    - pytest==7.1.1
    - scipy==1.8.0
    - pysiaf==0.15.0
    - matplotlib==3.5.1
    - tk>=0.1.0